version: 2
jobs:
  build:
    docker:
      - image: haskell:latest

    steps:
      - checkout

      - run:
          name: Compile
          command: stack build

      - run:
          name: Install
          command: stack install

      - run:
          name: Push to VPS
          command: scp /root/.local/bin/koscbot-exe $USERNAME@$SERVER_IP:$SERVER_PATH

      - run:
          name: Restart bot
          command: killall koscbot-exe && ./koscbot-exe &
