version: 2
jobs:
  build:
    docker:
      - image: haskell:latest

    steps:
      - checkout

      - run:
          name: Compile
          command: stack build

      - run:
          name: Install
          command: stack install

      - run:
          name: Install scp
          command: apt update; apt install -y openssh-client

      - run:
          name: Make .ssh dir
          command: mkdir ~/.ssh

      - run:
          name: Add server to known_hosts
          command: ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts

      - run:
          name: Stop currently running bot
          command: ssh $USERNAME@$SERVER_IP "pidof koscbot-exe && killall koscbot-exe || echo 'Bot is not running yet'"

      - run:
          name: Push to VPS
          command: scp /root/.local/bin/koscbot-exe $USERNAME@$SERVER_IP:$SERVER_PATH

      - run:
          name: Export bot token and start bot
          command: ssh $USERNAME@$SERVER_IP "export BOT_TOKEN=$BOT_TOKEN; nohup $SERVER_PATHkoscbot-exe > log.out 2> log.err < /dev/null &"
