version: 2
jobs:
  build:
    docker:
      - image: haskell:latest

    steps:
      - checkout

      - run:
          name: Compile
          command: stack build

      - run:
          name: Install
          command: stack install
